name: Autopilot
on:
  workflow_dispatch:

jobs:
  update-composer:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Run Composer Update
        run: composer update --no-interaction --no-progress

      - name: Commit and push changes to autopilot branch
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

          # Fetch all branches
          git fetch origin

          # Verificar si el branch 'autopilot' existe en remoto
          if git ls-remote --exit-code --heads origin autopilot; then
            git checkout -B autopilot origin/autopilot
          else
            git checkout -B autopilot
          fi

          # Agregar composer.lock solo si existe
          if [ -f composer.lock ]; then
            git add composer.lock
          fi

          # Obtener la fecha actual
          DATE=$(date +'%Y-%m-%d')

          # Hacer commit solo si hay cambios
          if git diff --cached --quiet; then
            echo "No hay cambios en composer.lock. No se hace commit."
          else
            git commit -m "Autopilot: Composer Update - $DATE"
            git push origin autopilot
          fi
