name: Autopilot
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'  # A las 00:00 UTC del día 1 de cada mes

jobs:
  update-composer:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Run Composer Update
        run: composer update --no-interaction --no-progress

      - name: Install wp-cli
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          chmod +x wp-cli.phar
          sudo mv wp-cli.phar /usr/local/bin/wp

      - name: Update WordPress Core
        run: wp core update
      
      - name: Update WordPress Themes
        run: wp theme update --all

      - name: Verificar cambios en wp-admin y wp-includes
        run: |
          git diff --exit-code wp-admin wp-includes || echo "Hay cambios en wp-admin o wp-includes."
      - name: Commit and push changes to autopilot branch
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

          # Fetch all branches
          git fetch origin

          # Verificar si el branch 'autopilot' existe en remoto
          if git ls-remote --exit-code --heads origin autopilot; then
            git checkout -B autopilot origin/autopilot
          else
            git checkout -B autopilot
          fi

          # Agregar cambios a los directorios wp-admin, wp-includes, wp-content y wp-content/themes
          git add wp-admin wp-includes wp-content wp-content/themes composer.lock

          # Obtener la fecha actual
          DATE=$(date +'%Y-%m-%d')

          # Hacer commit solo si hay cambios
          if git diff --cached --quiet; then
            echo "No hay cambios en wp-admin, wp-includes, wp-content o wp-content/themes. No se hace commit."
          else
            git commit -m "Autopilot: Composer Update & WP Core Update - $DATE"
            git push origin autopilot
          fi
