on:
  workflow_dispatch:  # Permite ejecución manual

name: Update WordPress Plugins and Push to Specific Branch

jobs:
  update-plugins:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Clona todo el historial de Git

    - name: Set up PHP and Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        tools: composer

    - name: Update Composer Dependencies
      run: composer update --no-dev --optimize-autoloader

    - name: Commit Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@github.com"
        git add composer.lock
        git commit -m "chore: update WordPress plugins via Composer" || echo "No changes to commit"

    - name: Push Changes to Specific Branch
      env:
        BRANCH_NAME: "plugin-updates"  # Cambia esto por el nombre del branch que desees
        GITHUB_TOKEN: ${{ secrets.TOKEN_IV }}
      run: |
        git push origin HEAD:$BRANCH_NAME
