name: WordPress Code Standard Validator

on:
  pull_request:
    branches:
      - master
jobs:
  phpcs_wordpress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer, phpcs

      - name: Install Composer dependencies
        run: composer install

      - name: Install WordPress Coding Standards
        run: |
          vendor/bin/phpcs --config-set installed_paths vendor/wp-coding-standards/wpcs
          vendor/bin/phpcs -i  # Verificar instalación

      - name: Run PHPCS on changed PHP files
        run: |
          # Obtenemos la lista de archivos PHP modificados entre la base del PR y el commit actual
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep '\.php$' || true)
          if [ -z "$CHANGED_FILES" ]; then
            echo "No PHP files changed."
            exit 0
          fi
          echo "Changed PHP files: $CHANGED_FILES"
          vendor/bin/phpcs --standard=WordPress,WordPress-Docs,WordPress-Extra $CHANGED_FILES
        
