name: PHP Code Review

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  code_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: phpstan, psalm, composer

      - name: Install dependencies
        run: composer install --no-progress --no-suggest

      - name: Run PHPStan (Static Analysis)
        run: phpstan analyse src --level=max

      - name: Run Psalm (Security & Type Checking)
        run: psalm

      - name: Upload Analysis Results
        uses: actions/upload-artifact@v3
        with:
          name: php-code-review-results
          path: reports/
