name: PHP Code Review (WordPress Theme)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  phpstan_phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: phpstan, phpcs, composer

      - name: Install dependencies
        run: composer install --no-progress --no-suggest || true

      - name: Run PHPStan (Static Analysis)
        run: vendor/bin/phpstan analyse wp-content/test --level=5 --memory-limit=1G

      - name: Run PHP CodeSniffer (Code Style & Formatting)
        run: vendor/bin/phpcs --standard=WordPress wp-content/test
