name: Improve Commit Message and Validate

on:
  push:
    branches:
      - '**'

jobs:
  improve-commit-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get last commit message
        id: get_message
        run: echo "msg=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT

      - name: Detect Spanish commit message
        id: detect_spanish
        run: |
          MSG="${{ steps.get_message.outputs.msg }}"
          if echo "$MSG" | grep -P '[áéíóúñÁÉÍÓÚÑ]' >/dev/null; then
            echo "spanish=true" >> $GITHUB_OUTPUT
          else
            echo "spanish=false" >> $GITHUB_OUTPUT
          fi

      - name: Improve and translate commit message with OpenAI
        if: steps.detect_spanish.outputs.spanish == 'true'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENIA }}
          MSG: "${{ steps.get_message.outputs.msg }}"
        id: improve_translate
        run: |
          REQUEST_BODY=$(jq -n --arg msg "$MSG" '{model:"gpt-4o-mini", messages:[{role:"user", content:"Improve and translate this commit message to English following Conventional Commits format: \($msg)"}]}')
          RESPONSE=$(curl https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d "$REQUEST_BODY" \
            | jq -r '.choices[0].message.content')
          echo "msg=$RESPONSE" >> $GITHUB_OUTPUT

      - name: Amend commit with improved message
        if: steps.detect_spanish.outputs.spanish == 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit --amend -m "${{ steps.improve_translate.outputs.msg }}"
          git push --force

  validate-commit-message:
    needs: improve-commit-message
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ahmadnassri/action-commit-lint@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pattern: '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test|release|deps|merge)(\\(.+\\))?: .+'

