name: Commit Lint

on:
  push:
    branches: 
      - 'autopilot'

jobs:
  check-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-commit-lint@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pattern: '^(feat|fix|docs|style|refactor|test|chore)(\(.+\))?: .+'