name: Check Commit Messages

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  semantic-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
            chore
            docs
            style
            refactor
            perf
            test
          scopes: ''