name: Check Commit Messages

on:
  push:
    branches:
      - 'autopilot'

jobs:
  semantic-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
            chore
            docs
            style
            refactor
            perf
            test
          scopes: ''