on: push
name: Push
jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
    
    - name: Setup SSH
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PANTHEON_SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Set up Pantheon Git Remote
      env:
        pantheon_repo: ${{ vars.PANTHEON_REPO }}
      run: |
        git remote add pantheon $pantheon_repo
    
    - name: Push to Pantheon
      run: |
        git push pantheon HEAD:master