name: Deploy to Pantheon (Dev Environment)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Pantheon Dev
      env:
        TERMINUS_MACHINE_TOKEN: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
        PANTHEON_SITE: ${{ secrets.PANTHEON_SITE_NAME }}
      run: |
        echo $TERMINUS_MACHINE_TOKEN
        echo $PANTHEON_SITE
