on: push
name: Push
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.PANTHEON_SSH_KEY }}

    - name: Set up Panthero Git Remote
      env:
        pantheon_repo: '${{ secrets.PANTHEON_REPO }}'
      run: |
        echo $pantheon_repo
        #git remote add pantheon $pantheon_repo
    
    - name: Push to Pantheon
      run: |
        echo $ssh-private-key
        echo $pantheon_repo