on: push
name: Push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup SSH
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PANTHEON_SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Set up Pantheon Git Remote
      env:
        pantheon_repo: ${{ vars.PANTHEON_REPO }}
      run: |
        git remote add pantheon $pantheon_repo || echo "Remote already exists"

    - name: Fetch and Rebase Changes
      run: |
        git fetch pantheon master
        git rebase pantheon/master || echo "No changes to rebase"

    - name: Push to Pantheon
      run: git push pantheon HEAD:master

    - name: Run Composer Install on Pantheon
      run: |
        ssh -p 2222 -o StrictHostKeyChecking=no codeserver.dev.36c52dec-49a8-4f16-b1bb-ba5301db5bf4.drush.in "cd ~/code && composer install --no-dev --optimize-autoloader"
