on: push
name: Push
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: shimataro/ssh-key-action@v2.4.0
      with:
        key: ${{ secrets.PANTHEON_SSH_KEY }}

    - name: deployer
      env:
        pantheon_repo: '${{ secrets.PANTHEON_REPO }}'
      run: |
        git remote add pantheon $pantheon_repo
        git push pantheon HEAD:master